---
- hosts: sns
  vars:
    hello: "Hello, World!"
    hello_file: "hello.txt"
  tasks:
  - name: create hello file
    template:
      src: "{{ hello_file }}.j2"
      dest: /tmp/{{ hello_file }}
  - name: "show {{ hello_file }}"
    command: "cat /tmp/{{ hello_file }}"

#
# [EOF]
#
